name: Kubernetes Deployment
 
on:
  push:
    branches:
      - main
 
jobs:
   build:
        runs-on: self-hosted
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

   deploy:
     runs-on: self-hosted
     needs: build
   
     steps:
       - name: Checkout
         uses: actions/checkout@v4
   
       - name: Azure Login
         uses: azure/login@v2
         with:
           auth-type: IDENTITY
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   
       - name: Get AKS Credentials
         run: |
           az aks get-credentials \
             --resource-group Gh-Action-Test \
             --name AKS-Gh-Action-Test \
             --overwrite-existing
   
       - name: Replace image tag
         run: |
           sed -i 's|IMAGE_PLACEHOLDER|${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}|g' aks-deployment.yaml
   
       - name: Deploy
         run: |
           kubectl apply -f aks-deployment.yaml
